language: python

python:
    - 2.7
    # - 3.4

sudo: false

addons:
    apt:
        packages:
            - gfortran

env:
    global:
        - ASTROPY_VERSION=dev
        - CONDA_DEPENDENCIES='click matplotlib'
        - PIP_DEPENDENCIES='pytpm novas pyephem starlink-pyast palpy'
        - SETUP_XVFB=True

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    - pip install https://github.com/scottransom/pyslalib/archive/master.zip
    - if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then
        pip install http://www.astro.rug.nl/software/kapteyn/kapteyn-2.3.tar.gz;
      fi

script:
    - ./make.py --help
    - ./make.py tool-info
    - ./make.py make_observer_table
    - ./make.py make_skycoord_table
    - ./make.py benchmark_celestial
    - ./make.py benchmark_horizontal
    - ./make.py summary_celestial
    # Making all plots is slow ... testing that plots work for two tools should be sufficient
    - ./make.py plots --tools astropy,pyast
