language: c

sudo: false

env:
    matrix:
        - PYTHON_VERSION=2.7 REQUIREMENTS_FILE=requirements.txt
        # - PYTHON_VERSION=3.6 REQUIREMENTS_FILE=requirements_python3.txt

addons:
    apt:
        packages:
            - gfortran

env:
    global:
        - ASTROPY_VERSION=dev
        - CONDA_DEPENDENCIES='click matplotlib'
        - SETUP_XVFB=True

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install -r $REQUIREMENTS_FILE

script:
    - ./make.py --help
    - ./make.py tool-info
    - ./make.py make_observer_table
    - ./make.py make_skycoord_table
    - ./make.py benchmark_celestial
    - ./make.py benchmark_horizontal
    - ./make.py summary_celestial
    # Making all plots is slow ... testing that plots work for two tools should be sufficient
    - ./make.py plots --tools astropy,pyast
    - ./make.py deploy
