language: python

python:
    - 2.7
    # - 3.4

before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

    # Make sure matplotlib uses PyQT not PySide
    - export QT_API=pyqt

    # Install gfortran for pyslalib
    - sudo apt-get install gfortran

install:

    # CONDA
    - conda create --yes -n test -c astropy-ci-extras python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # CORE DEPENDENCIES
    - conda install --yes numpy pip Cython jinja2 pyqt matplotlib
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -r requirements.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install -r requirements_python3.txt; fi

script:
    - ./make.py --help
    - ./make.py tool-info
    - ./make.py make_observer_table
    - ./make.py make_skycoord_table
    - ./make.py benchmark_celestial
    - ./make.py benchmark_horizontal
    - ./make.py summary_celestial
    # Making all plots is slow ... testing that plots work for two tools should be sufficient
    - ./make.py plots --tools astropy,pyast
